# testthat snapshots are machine-generated regression tests that
# have to be preserved exactly as they are
exclude: '^tests/testthat/_snaps/.*$'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: fix-byte-order-marker
    -   id: check-added-large-files
        args: ['--maxkb=100']
    -   id: mixed-line-ending

-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.3.2.9021
    hooks:
    -   id: parsable-R
    -   id: no-browser-statement
    -   id: no-debug-statement
ci:
    autoupdate_schedule: quarterly
